'use client'
import { Container, ThemeProvider, createTheme } from '@mui/material'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const theme = createTheme({
  palette: {
    primary: {
      main: '#D5B263',
      // light: will be calculated from palette.primary.main,
      // dark: will be calculated from palette.primary.main,
      // contrastText: will be calculated to contrast with palette.primary.main
    },
    secondary: {
      main: '#293040'
    },
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Quizify</title>
        <meta name='description' content='quiz app for your children' />
      </head>
      <body className={inter.className} style={{ margin: 0 }}>
        <ThemeProvider theme={theme}>
          <Container sx={{
            bgcolor: 'secondary.main',
            height: "100vh",
          }} maxWidth={'false'}>
            {children}
          </Container>
        </ThemeProvider>
      </body>
    </html>
  )
}
